apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: jupyter
  namespace: jupyter
spec:
  network:
    expose:
      - service: proxy-public
        podLabels:
          component: proxy
        host: notebook
        gateway: tenant
        port: 80

    allow:
      - direction: Ingress
        remoteGenerated: Anywhere

      - direction: Egress
        remoteGenerate: Anywhere
---
# Source: istio/templates/bigbang/peerAuthentication.yaml
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-istio-system
  namespace: jupyter
spec:
  mtls:
    mode: PERMISSIVE