name: Publish singleuser image

permissions:
  contents: read

on:
  push:
    tags:
      - "singleuser-*"

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.inputs.branchName }}

      - name: "Login to GHCR"
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ github.token }}

      - name: Get tag
        run: |
          echo TAG=$(string="singleuser-0.1.0"; echo "${string#singleuser-}") >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@35e7dd592106dcd929ef8706706f6d54678d1f67 # v5.3.0
        with:
          context: singleuser-image
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/defenseunicorns/uds-package-jupyter/singleuser:${{ env.TAG }}